import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "@/app/_components/common/ToastProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.className}   bg-[#140327] text-white max-w-screen  overflow-x-hidden`}
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
